### ISSUE TITLE
Connection failed!

### ISSUE THREAD

**Issue by MaDiBmDaD** [PlusToolkit/PlusMatlabUtils#2]
Hi, what should select as a configuration file that connects to a tracking device?NDI folder contains ToolBox but it seems this address is not the right one in Plus Server Launcher.

**Comment by adamrankin** [comment]
What configuration file are you trying to connect with? If it's not a sample config file, could you upload it for us to examine?

(also, we generally look at issues in https://github.com/PlusToolkit/PlusLib)

**Comment by MaDiBmDaD** [comment]
Im trying for NDI Polaris tracker with passive markers. In the default folder PlusApp-.../config there are three subfolders that I added NdiToolDefinitions! Does it seem I have to add some more information from my device Polaris to PlussApp?

**Comment by adamrankin** [comment]
Ok, which config file did you use to connect?

**Comment by MaDiBmDaD** [comment]
I use Polaris Vega, I found one folder named "config" in the source installed file ToolBox on windows but it seems wrong and not acceptable.

**Comment by MaDiBmDaD** [comment]
BTW I am inclined to use ethernet instead of COM, is it possible to use Plus Server? If not I prefer to work with NDICAPI.

**Comment by adamrankin** [comment]
There is an example config file in the Plus toolkit for Vega. You can either use IP or Bonjour, depending on how your Vega is configured.

Plus is just a wrapper to NDICAPI, so feel free to use whichever works for you.

**Comment by MaDiBmDaD** [comment]
Is there any example such as ndiBasicExample(cpp) for Vega? I could not see in the Application folder in ndicapi!

**Comment by MaDiBmDaD** [comment]
I already replaced ndiOpenNetwork and ndiCloseNetwork in ndiBasicExample(cpp) but still thinking about other settings that I missed in adaption of the serial port in it!

**Comment by adamrankin** [comment]
Nope, that's it. All other commands are the same.

**Comment by lassoan** [comment]
This issue is stale and does not seem to be related to the OpenIGTLink Matlab interface, therefore closing it now.
