### ISSUE TITLE
Send transform from 3D slicer to matlab

### ISSUE THREAD

**Issue by Matteo-0** [PlusToolkit/PlusMatlabUtils#4]
Hello,
I am trying to send a transform from 3D slicer to matlab and I followed the steps in the examples but nothing works and in matlab I keep reading "no transforms are available"

How do I solve this problem?

**Comment by lassoan** [comment]
We don't actively maintain the OpenIGTLink interface for Matlab. We switched to Python and provide the [pyigtl](https://pypi.org/project/pyigtl/) package for communicating via OpenIGTLink from custom processing scripts.

You can either use this Python package from Matlab; or update the scripts in this repository to work with current OpenIGTLink version (and send a pull request with the changes, just in case there are others who still use Matlab).
